# image:
#   file: .gitpod.Dockerfile

tasks:
  - init: brew install sqlite3 curl && exit
  - init: npm i -g npm-check-updates && exit
  - init: yarn && yarn test

vscode:
  extensions:
    - firsttris.vscode-jest-runner
    - gengjiawen.vscode-postfix-ts
    - gengjiawen.vscode-npm-dependency
    - gengjiawen.npm-dependency-links
